### ISSUE TITLE
Rewards cannot be correctly calculated from Bee side after the claim phase

### ISSUE THREAD

**Issue by swarmHaseeb** [ethersphere/storage-incentives#109]
Currently there are 2 possible ways to calculate rewards:

1. Call the total pot before a claim is made: 
Demerits: TotalPot also calls the expiry func within contract and it can actually change the value of pot.
2. Compare the before and after balance of the wallet:
Demerits: Someone can transfer funds during that time which could result in incorrect value of rewards.

Possible Solution:
1. Export the value of Pot
function currentPot() public view returns (uint256) {
        return pot;
    }
Demerits: not sure if exporting a pot while the game is happening is a good idea.
2. Save pot to a private variable prevPot, reset the original pot and then return the prevPot from withdraw function without exporting anything.
Demerits: Can't see any

**Comment by swarmHaseeb** [comment]
@metacertain @istae for kind notice

**Comment by significance** [comment]
rewards can be determined from emitted events
