### ISSUE TITLE
investigate the state of the contract when there is at least one commit, reveal, but no claim trx

### ISSUE THREAD

**Issue by istae** [ethersphere/storage-incentives#122]
each phase carries a state from the previous phases
for example, if there some commit and reveal trx, but no claim trx, what is the behavior of the contract?

**Comment by n00b21337** [comment]
Commit
1. If commit trx comes late, it will be reverted as conditions will not pass so there is no possible harm done there
2. There is no penalty for the user, he will just lose the chance to get a reward
3. There is no state change here that could be a problem

Reveal
1. Should not run if called late/not in proper time, there is no critical state change there
2. Why do we construct obfuscatedHash in the reveal and just put ready-made in a commit phase?
3. Can be called in different rounds as there is no round check, but will revert as no matching commits will be found with commitHash as it changes each round

Claim
1. Refactor claim function, duplicate code with isWinner
2....

**Comment by n00b21337** [comment]
Questionable code here as it seems it will always be true and never freezing because its set to that before in previous loop

```
 if (
                    truthRevealedHash == currentReveals[revIndex].hash &&
                    truthRevealedDepth == currentReveals[revIndex].depth
                )
```
