### ISSUE TITLE
allow immutable batches to be dilutable (depth increase)

### ISSUE THREAD

**Issue by istae** [ethersphere/storage-incentives#156]

**Comment by crtahlin** [comment]
As from forum communication, quoting:

"the restriction is actually in the contract https://github.com/ethersphere/storage-incentives/blob/master/src/PostageStamp.sol#L270"

**Comment by mfw78** [comment]
Actually, access controls around stamps in general needs revision.

If all batch types can be diluted, if the EOA that owners the batch becomes compromised, an adversarial actor can dilute the batch greatly, significantly reducing it's `ttl`, and opening up a potential censorship vector.

eg. Alice has uploaded data that is damaging to Eve. Eve, through some method, acquires Alice's EOA's private key, dilutes the batch, with the content being garbage collected from Swarm.

**Comment by n00b21337** [comment]
> As from forum communication, quoting:
> 
> "the restriction is actually in the contract https://github.com/ethersphere/storage-incentives/blob/master/src/PostageStamp.sol#L270"
> 
> This feature is quite important for uploading data, when you want to enlarge the stamp after the fact.
> 
> Please prioritize to be included soon.

We can include this in the next Stamp release.  Will talk with others about it.

The fact is that only place that immutableFlag is used in contracts is at that line in increaseDepth function
` require(!batch.immutableFlag, "batch is immutable");`
so in essence we are removing any use of immutableFlag in the contract.

**Comment by mfw78** [comment]
I somewhat actually disagree. If the logic of re-uploading again after the fact is to be used, well then this points to leave immutable as only immutable, no? ie. if you want a larger batch, purchase a new one. And if you want the option to increase it's depth later, set it as not immutable.

**Comment by n00b21337** [comment]
I'm not entirely clear on your stance. What would you suggest we do?

**Comment by mfw78** [comment]
Immutable is immutable. On-chain state shouldn't be mutable if you set it as immutable. This isn't logical. 

If the user wants to upload more content, buy another stamp.

**Comment by crtahlin** [comment]
My suggestion to cover the use case would be to either allow dilution of immutable stamp (which is disputable) or add an additional parameter "dilutable" (which would not be disputable?).

**Comment by istae** [comment]
@mfw78 what also sets apart immutable from mutable batches is that immutable batches do not allow overriding of previously uploaded chunks when the batch becomes fully utilized. I would say that diluting immutable batches is a very useful feature for when the batch does become full, you can simply topup and dilute to make room for more chunks while maintaining  the guarantee that future uploads do not override past data.

**Comment by istae** [comment]
@zelig has said that immutable batches should be dilutable.

**Comment by n00b21337** [comment]
We are going to deploy new stamp with PH4 so lets solve this one before that and have the solution applied.

**Comment by istae** [comment]
perfect!

**Comment by n00b21337** [comment]
Ok just to get into action here
https://github.com/ethersphere/storage-incentives/blob/ca6433a5152bff5d2506aafb3312286e85a87b08/src/PostageStamp.sol#L347C5-L349C10

or

```
        if (batch.immutableFlag) {
            revert BatchIsImmutable();
        }

```

we want to remove this so depth can be increased on bathes that already exists. 

Do we want to do anything more?  When this is removed at least on the contract context
immutableFlag  is then just more as parameter, not used for anything, do we need to use it for something other?

**Comment by istae** [comment]
i think that's it...

**Comment by n00b21337** [comment]
Ok this has been added to master, will be release in upcoming PH4.
