### ISSUE TITLE
feat: return `batchId` on create

### ISSUE THREAD

**Issue by mfw78** [ethersphere/storage-incentives#167]
**Problem**:

Refer to: https://github.com/ethersphere/storage-incentives/blob/e97ec1033843dbd373857597332e43dfc209806c/src/PostageStamp.sol#L140

In this signature, the `batchId` isn't being passed back to the caller. There is a strong assumption here that `createBatch` is, and will only ever, be called by an EOA. Otherwise, given the batch, a caller from another contract would then have to calculate the `batchId` themselves if they wanted to make use of this.

**Solution**

Return the `batchId` on `createBatch`. Gas costs for doing so are negligible when compared with the case of having to recalculate in a calling contract.

**Comment by n00b21337** [comment]
We can add this if this is still something that is deemed useful. Should we add it?

**Comment by n00b21337** [comment]
https://github.com/ethersphere/storage-incentives/pull/225

here

**Comment by n00b21337** [comment]
Added
