### ISSUE TITLE
Streamline deployments

### ISSUE THREAD

**Issue by n00b21337** [ethersphere/storage-incentives#193]
As we didnt move to any proxy kind of updates for our contracts and are fixed on migration as way of upgrading we have an issue with how we work.

The main problem is a master branch and how we merge to it, as what we have now is few upgraded contracts there but they are not deployed. What happens then is that our exports for bee node cant be automated as exports are done on a whole contract suite basis.
So to deploy we need to do some code gymnastics and manual work to put proper info into deployed exports and be sure that its correct.
Another problem is integrations between contracts, state in master is not something that is onchain, so when we code we cant relay on what we build on top of and need to check what is actually running and will  be running once we deploy. Example redis contract used some of methods that are added to master for postagestamp but that are not onchain, so we need to accommodate for that and use different code to make it work as we are not migrating postagestamp so easily.

Solutions
First, we must lock master to be in a state that is equal to deployed contracts, which means we shouldn't merge our PRs to master until we are sure they are about to be deployed.
The second thing is that we need to have a place where we can merge finished PRs so they are not cluttering UI and we know they are done. We could have a gitflow develop kind of branch but this will also be a blocking thing as we might finish task for postagestamp contract, merge it and then after that we merge oracle PR, we want to deploy just oracle and then we have the same problem as now. 
So what comes to mind is that as we are bound by our 4 contracts we make running develop branches for each of them and we have a place to merge when something has been done but not blocking other contracts in process. When we want to deploy any of the upgrades for that contract we merge that develop branch into the master.
For tooling/config improvements we can always just merge to master that is not an issue.

**Comment by ct-ctrl** [comment]
I know I was always in favour of the proxy solution, but your proposal for 4 running branches or basically a branch per EPIC/work package is interesting and would keep it clean. 
Only thought is, does that cause a bottleneck at the time of master merge when there's a lot of conflicts built up? 
But this or something like it is a good idea, let's definitely get streamlined for the erasure codes going forward.

**Comment by nugaon** [comment]
We are looking for some kind of GitHub workflow action here that does proper versioning, tagging, change-log management and also can trigger deployment scripts.

The release workflow that we are using for JS developments is called [Release Please](https://github.com/google-github-actions/release-please-action) which is also aligned with the conventional commit messages. It supports monorepo use-case so it can be set to create appropriate release PRs when some of the files had changes on some specific branch (e.g. [this](https://github.com/fairDataSociety/fdp-contracts/pull/135) and [this](https://github.com/fairDataSociety/fdp-contracts/pull/154). Thereby, it enforces proper separate self-contained PRs as well.

**Comment by n00b21337** [comment]
> I know I was always in favour of the proxy solution, but your proposal for 4 running branches or basically a branch per EPIC/work package is interesting and would keep it clean. Only thought is, does that cause a bottleneck at the time of master merge when there are a lot of conflicts built up? But this or something like it is a good idea, let's definitely get streamlined for the erasure codes going forward.

There shouldn't be lot of conflicts built up in that case, as each branch would be worked mostly on a separate file. Also we should update always develop branches to master while in progress as we want to build on top of current state asa much as possible. I dont see a problem here with this way and should suite our demands.

**Comment by n00b21337** [comment]
> We are looking for some kind of GitHub workflow action here that does proper versioning, tagging, change-log management and also can trigger deployment scripts.
> 
> The release workflow that we are using for JS developments is called [Release Please](https://github.com/google-github-actions/release-please-action) which is also aligned with the conventional commit messages. It supports monorepo use-case so it can be set to create appropriate release PRs when some of the files had changes on some specific branch (e.g. [this](https://github.com/fairDataSociety/fdp-contracts/pull/135) and [this](https://github.com/fairDataSociety/fdp-contracts/pull/154). Thereby, it enforces proper separate self-contained PRs as well.

I am not sure about this. Seems to me this workflow is more connected to trunk based development which is the opposite of what we do here as we have long-lived branches and PRs and don't deploy anything for very long periods of time.  Would like to hear a detailed proposal of this and how it can tackle the issues I mentioned.

**Comment by n00b21337** [comment]
Not to overcomplicate this, think we just need to adhere to the tagging system and use RCs and tags only when something is deployed to the chain. Which is actually fine in SI but not in some other SC repos.
Practice should be that when we do want to actually deploy something to the chain, we need to branch out of master but also from the latest tag.

For example, when we want to deploy a new Oracle contract but not any others, there is no point in using the current master if it is not the same for all contracts as the latest tag. 
We need to go to the latest tag, make updates to Oracle, and then deploy.
