### ISSUE TITLE
currentRoundAnchor() returns 0?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/storage-incentives#195]
In the 1.18.0-rc1 goerli testnet, currentRoundAnchor() is returning zero when in the commit and reveal phases.   In the claim phase, it seems to be returning the proper (non-zero) value for the upcoming round.

Contract: 0x9e3BDb0c69838CC06D85409d4AD6245e54F70F1d

**Comment by ldeffenb** [comment]
![image](https://github.com/ethersphere/storage-incentives/assets/5175026/84bc2198-3437-4e80-9286-7a8372037142)
![image](https://github.com/ethersphere/storage-incentives/assets/5175026/eb93b3a6-bfee-403d-86ee-74f30f333c58)

**Comment by n00b21337** [comment]
Trying to repeat that. So far I couldn't.

![image](https://github.com/ethersphere/storage-incentives/assets/8969767/e420923c-5d69-465c-8c1e-3f116b0c0423)

**Comment by n00b21337** [comment]
Ok I did it now. Checking for more info...

**Comment by n00b21337** [comment]
This is the desired behavior. None of the conditions apply so it returns 0x0
We did remove the revert used before for those cases, but maybe we should return it if this is confusing and ppl need to have it revert and say "can't return value after first reveal"

**Comment by n00b21337** [comment]
You can see that we dont get any anchor also from the current mainet implementation as well.
So its just the thing how we want to inform the users and nodes about this

![image](https://github.com/ethersphere/storage-incentives/assets/8969767/8b103bb6-d07d-43a6-be75-a7d062186db3)
