### ISSUE TITLE
Throw on external calls from contracts

### ISSUE THREAD

**Issue by n00b21337** [ethersphere/storage-incentives#211]
Exeternal calls to contracts should have way to show what is wrong when they fail. For this call and others

https://github.com/ethersphere/storage-incentives/blob/7cdfd9ce254c368c9cee0955095e4992bb61af06/src/Redistribution.sol#L472C9-L472C56

```
(bool success, bytes memory data) = addressB.call(abi.encodeWithSignature("functionName(args)"));
if (!success) {
    // Handle failure
    bytes memory actualErrorData = sliceBytes(data, 4);  // Removing the first 4 bytes that represent the function selector
    // Handle the error based on `actualErrorData`
}

```
or

```
try PostageContract.withdraw(winnerSelected.owner) {
    // This block will execute if the withdrawal is successful
    // You can put code here to handle the success case, if needed
} catch Error(string memory reason) {
    // This block will execute if there was an error with the withdrawal
    // 'reason' contains the error message/revert reason
    // You can put code here to handle the error, log it, etc.
    emit WithdrawalFailed(reason);
} catch (bytes memory lowLevelData) {
    // This is for errors that don't return a reason string
    // 'lowLevelData' contains the raw error data
    // You can put code here to handle this specific error case, log it, etc.
    emit WithdrawalFailed("Low-level error occurred.");
}
```

**Comment by n00b21337** [comment]
This actually wont help much. If there is a custom error, then it will just again throw bytes data, so best we can do here is. Emit string that says some default value and again still check bytecode error. This needs to be solved on the application level.
Etherescan currently doesnt solve it, can be caught with trace.  Tenderly solves this nicely as it should.

**Comment by mfw78** [comment]
Is the root problem you're trying to address causing issues on Gnosis Chain?

**Comment by n00b21337** [comment]
This is on PH4 we are currently working on and ways to debug reverts. But this solution and idea wasnt right, tested it and it didnt make sense to do it this way, the result is the same. Conclusion is just to use better debugging tools like tenderly
