### ISSUE TITLE
"Truth" selection busted?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/storage-incentives#40]
I have 4 nodes playing in the storage incentives on the testnet running 1.9.0.   In a recent round, I captured the following state during the claim phase.

Four nodes revealed their committed hashes.  The first node was only depth 1 while the next three nodes were all depth 2 and matched each other:

```
[ currentRoundReveals method Response ]
    tuple[] :  
[0xDb0690cd5c0cf749B33Ec15AFcd051020901559f,0xae9dc64b58c662b432851ce1f7b9ddd44b43c22dd1ea42adb692adac0f0e1279,100000000000000000,200000000000000000,0xdd022f9c85c465d43f16f71659dbc17cf45e57be20637c04b66ab2ecf9fbfc85,1]

[0x9878C68b482C59cA7EBE39DDc32cBC27504B69FB,0xd61a7f6794c09881603b9d927752d71536bbcbbeb101b78e1dd221712d607d7e,100000000000000000,400000000000000000,0x912115d4a5ea7eaa0211c17a107f36b5626fb6dac4b4ff6f9390cbe7ed5db0b6,2]

[0x62B32288D5292708de7443f78F6714C95E4C75FF,0xdf6c1b18cc21d07e0b89b05d16153002037f76982709ff879f2e6d60de7d2127,100000000000000000,400000000000000000,0x912115d4a5ea7eaa0211c17a107f36b5626fb6dac4b4ff6f9390cbe7ed5db0b6,2]

[0x830e313CCab2140F72cBfe2dC44BBE0014CD245B,0xe1dc994c4a8ba82c183cd9b773210d7c88061c507fb9a9dfcbccea04b8380134,150000000000000000,600000000000000000,0x912115d4a5ea7eaa0211c17a107f36b5626fb6dac4b4ff6f9390cbe7ed5db0b6,2]
```
But yet the SINGLE node at only depth one was apparently randomly declared the "truth" for the round and ended up winning the round!

```
[ winner method Response ]
  owner   address :  0xDb0690cd5c0cf749B33Ec15AFcd051020901559f
  overlay   bytes32 :  0xae9dc64b58c662b432851ce1f7b9ddd44b43c22dd1ea42adb692adac0f0e1279
  stake   uint256 :  100000000000000000
  stakeDensity   uint256 :  200000000000000000
  hash   bytes32 :  0xdd022f9c85c465d43f16f71659dbc17cf45e57be20637c04b66ab2ecf9fbfc85
  depth   uint8 :  1
```

Here's the events that show the other THREE MATCHING solutions all being frozen because they disagreed with the randomly selected "truth" only held by a single node.

https://goerli.etherscan.io/tx/0xef7ea56481792a95e06df9e149845f2f45081a24c362ac210c461dea12b18aec#eventlog

Is this expected behavior or is the truth determination going to actually take into account how many nodes/total stake are holding to a single "truth"?

**Comment by ldeffenb** [comment]
"Truth" determination code in effect at the time of this capture in contract:
https://goerli.etherscan.io/address/0xf4963031e8b9f9659cb6ed35e53c031d76480ead#code
```
        for(uint i=0; i<revealsArrayLength; i++){
            currentSum += currentReveals[i].stakeDensity;
            randomNumber = keccak256(abi.encodePacked(truthSelectionAnchor, i));

            randomNumberTrunc = uint256(randomNumber & MaxH);

            // question is whether randomNumber / MaxH < probability
            // where probability is stakeDensity / currentSum
            // to avoid resorting to floating points all divisions should be
            // simplified with multiplying both sides (as long as divisor > 0)
            // randomNumber / (MaxH + 1) < stakeDensity / currentSum
            // ( randomNumber / (MaxH + 1) ) * currentSum < stakeDensity
            // randomNumber * currentSum < stakeDensity * (MaxH + 1)
            if ( randomNumberTrunc * currentSum < currentReveals[i].stakeDensity * ( uint256(MaxH) + 1 ) ) {
                truthRevealedHash = currentReveals[i].hash;
                truthRevealedDepth = currentReveals[i].depth;
            }
        }

        emit TruthSelected(truthRevealedHash, truthRevealedDepth);
```

**Comment by nagydani** [comment]
> Here's the events that show the other THREE MATCHING solutions all being frozen because they disagreed with the randomly selected "truth" only held by a single node.
> 
> https://goerli.etherscan.io/tx/0xef7ea56481792a95e06df9e149845f2f45081a24c362ac210c461dea12b18aec#eventlog
> 
> Is this expected behavior or is the truth determination going to actually take into account how many nodes/total stake are holding to a single "truth"?

"Truth" is randomly selected with a probability proportional to the stakes. Thus, the majority stake *usually* ends up being selected as "truth", but not always. What happened to you can, indeed, happen by design.

The reason for this is that we want to prevent risk-free attacks of outstaking a neighborhood. If there is disagreement in a neighborhood -- which normally shouldn't happen -- someone will get frozen, more likely the minority. But not always.

**Comment by nagydani** [comment]
> Worse, as the currentSum increases as the loop runs, it seems to give more chance to the earlier reveals to be selected as the truth since the left side of the < comparison will be increasing along with currentSum while the right side is only based on a single revealed entry's stake.

No, that is not true. Earlier reveals have a greater probability of being selected, but also a greater probability of being overwritten. In effect, the truth oracle is selected randomly with a probability proportional to the stake, irrespective of the reveal order.

**Comment by significance** [comment]
> Worse, as the currentSum increases as the loop runs, it seems to give more chance to the earlier reveals to be selected as the truth since the left side of the < comparison will be increasing along with currentSum while the right side is only based on a single revealed entry's stake.

i initially thought this too, but there is a clever statistical trick employed!

> The used algorithm is a special case of Algorithm R from 3.4.2. of the same volume (Seminumerical Algorithms, The Art of Computer Programming by Don Knuth) for n=1. It is credited to Alan G. Waterman.

i'm yet to actually pull this up but i believe this is used. basically every iteration is counter-weighted so the probabilities end up matching proportionally with earlier iterations. very smart indeed 🙇 

@ldeffenb we're cleaning up the repo dude, ok to close this?

**Comment by ldeffenb** [comment]
Yep, we can close this here and I'll keep watching the behavior of the the game.   It'll be more interesting when it finally gets to mainnet as I'm hoping there'll be more participants in each round than we've seen in testnet.
