### ISSUE TITLE
Claim is blockheight dependent

### ISSUE THREAD

**Issue by significance** [ethersphere/storage-incentives#43]
If the user cannot get a transaction into the optimal block then they are inadvertently punished.

It would be fairer to retain the reward and allow this to be claimed on a round id basis at any point in the future.

**Comment by ldeffenb** [comment]
Actually, I thought the pot keeps growing until a claim is actually made?   At least, that's what I've observed in the testnet.   Consider:

Round   Reward
51775  54.6T (that's trillion plur)
51776  37.8T
51777  46.5T
51778 unclaimed
51779  93.5T - Note the double reward?
51780  47.6T
51781 unclaimed
51782  94.3T - again a double reward
51783 unclaimed
51784  98.4T - and yet again
51785  48.9T
51786  49.0T
51787  unclaimed
51788  0.010 gBZZ (that's 100+T)
51789 unclaimed

monsi makes this easy to watch!  https://github.com/rndlabs/monSI

**Comment by ldeffenb** [comment]
Unless by "optimal block" you mean a specific target within a single round's claim phase?

**Comment by significance** [comment]
yes, indeed! i think we decided that this was an avenue for client optimisation ;D
