### ISSUE TITLE
potential pot uint256 underflow bug 

### ISSUE THREAD

**Issue by istae** [ethersphere/storage-incentives#51]
in the postage stamp contract, the pot is a uint256
in expire we do this pot += batchSize * (batch.normalisedBalance - leb); 
where batch.normalisedBalance - leb could be a negative number

if the pot at that moment is less than batchSize * (batch.normalisedBalance - leb), that could be an underflow bug

**Comment by significance** [comment]
> Since Solidity 0.8.0, all arithmetic operations revert on over- and underflow by default.
