### ISSUE TITLE
Minimum bucket depth in the PostageStamp contract

### ISSUE THREAD

**Issue by agazso** [ethersphere/storage-incentives#56]
In the current version of the PostageStamp contract there is a check for the bucket depth to be bigger or equal than the minimum batch depth:

https://github.com/ethersphere/storage-incentives/blob/eb69a5fb2fb146abe20c35a8178addf32cd6463a/src/PostageStamp.sol#L135

I see several issues with this, logically and coding-wise as well:
- It is not clear what is the reasoning behind this and why that number is chosen 
- The comparison happen between the `minimumBatchDepth` and the `bucketDepth` and therefore the former defines the upper bound for the latter. This creates an implicit invariant in the code that is hard to understand without fully understanding the contract code.
- It is possible to set the minimum batch depth with a helper function. Because of the previously mentioned invariant this implicitly affects the minimum bucket depth as well: https://github.com/ethersphere/storage-incentives/blob/eb69a5fb2fb146abe20c35a8178addf32cd6463a/src/PostageStamp.sol#L437

My suggestions to improve this:
- Write down the relationship between the `minimumBatchDepth` and the `bucketDepth` and why the defaults are chosen as such, preferably in comments.
- Consider using different values for the two, maybe not both needs to be able to change after the contract is created.

**Comment by mrekucci** [comment]
The check is no longer part of the requirements.
