### ISSUE TITLE
Documentation needs update

### ISSUE THREAD

**Issue by tfius** [ethersphere/storage-incentives#58]
Deployment address for postageStamp deployment address on xDai 
`0x6a1A21ECA3aB28BE85C7Ba22b2d6eAE5907c900E` 

While in https://github.com/ethersphere/bee/blob/master/pkg/config/chain.go it is specified as  `0xa9c84e9ccC0A0bC9B8C8E948F24E024bC2607c9A` 

Also for Goerli deployment address mismatch:

> in chain.go - `0xf0a7e63f72a73bd339a7ee814aefa80995e532a0`
> in storage-incentives readme its `0x621e455C4a139f5C4e4A8122Ce55Dc21630769E4`

**Comment by mrekucci** [comment]
The addresses can now be found in the testnet_deployed.json and mainnet_deployed.json files. The corresponding code (which bee will use) will also be generated from these files. For more, see #68.
