### ISSUE TITLE
redistribution contract is freezing stakes although all samples are matching in a round 

### ISSUE THREAD

**Issue by istae** [ethersphere/storage-incentives#67]

**Comment by significance** [comment]
@istae have you got any specific examples of this?

**Comment by istae** [comment]
storage incentives agent
https://monitoring.testnet.ethswarm.org/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22private-testnet%5C%22%7D%20%7C%3D%20%60storageincentives%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221669863031000%22,%22to%22:%221669868771000%22%7D%7D

sampler logs
https://monitoring.testnet.ethswarm.org/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22private-testnet%5C%22%7D%20%7C%3D%20%60sampler%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221669863031000%22,%22to%22:%221669868771000%22%7D%7D

reserve sizes
https://monitoring.testnet.ethswarm.org/d/Szc9zJUGk/localstore?orgId=1&from=1669863031000&to=1669868771000&var-namespace=private-testnet&var-instance=All

**Comment by istae** [comment]
full-4-bee-3 produces hash bd99bb385f55a280e86bb1410364afd7ea174ff022f106a246b050f61c66face at "time"="2022-12-01 02:52:27.412968"

|2022-12-01 06:59:03 | "time"="2022-12-01 03:59:03.638884" "level"="error" "logger"="node/storageincentives" "msg"="make sample" "error"="IsPlaying: overlay 0xf641288a8fdfde68560033017d25118d14703eb6deef086bacb248bf2cac409b depth 1: execution reverted: stake updated recently

then it's stake is frozen

[8:50 AM](https://beehive.ethswarm.org/swarm/pl/hdiy7ksgab8rica6s7g7wb7x8w)



you can see that the samples in each round match
