### ISSUE TITLE
contracts modules & upgradability process/feasibility needs defined 

### ISSUE THREAD

**Issue by ct-ctrl** [ethersphere/storage-incentives#82]
below are notes on contract maintainability concerns from 3 issues.

we should discuss and find an acceptable way forward, then implement.

...

The contracts will be upgraded potentially numerous times and eventually have roles revoked. 

Therefore before release, we need to understand their upgradability and how to go about this and swap out contracts modules. 

Or, understand if a full set of contracts needs stopped and a new set is deployed and what can occur in the interim. 

**Create methods that enable the admin role to change the references of linked contracts**

as well as implementing ph4, we will potentially need to redeploy contracts for upgradability purposes

it is important to find a way to do this that does not affect user security assumptions

The deployment script should be able to deploy an individual branch in the smart contract tree.

The smart contract tree is the following: BzzToken -> Staking -> PostageStamp -> PriceOracle -> Redistribution.

**Comment by n00b21337** [comment]
We are set on full migration as an upgradability approach, no proxies are involved.

**Comment by mfw78** [comment]
Not having a method of pointing to canonical contracts as there are subsequent deployments, is a noticeable pain point for any integration.

**Comment by n00b21337** [comment]
Personally I am/was for using proxy contracts and possible time locks for updates( add some kind of governance even at some point) but executive decision has been made not do to that so we will use migrations and changing of contracts addresses as way of improvements.
