### ISSUE TITLE
Implement London transaction

### ISSUE THREAD

**Issue by mrekucci** [ethersphere/storage-incentives#87]
Add a smart contract deployment script that will use the new EIP-1559 (London) transaction.

**Comment by n00b21337** [comment]
Connecting current PR
https://github.com/ethersphere/storage-incentives/pull/92/commits

**Comment by n00b21337** [comment]
![Screenshot from 2023-03-09 08-30-57.png](https://images.zenhubusercontent.com/640746a421238e2a06909e41/902ff6c0-3910-4905-b574-8729b583712b)

To make this task it is needed to update libraries used with hardhat as most of them are outdated as seen from the image above and the current state. I would do this in another branch as the previous guy did this but also added some others and not sure if he updated all properly.  Also, the task should be split into 2 things. The whole scripts deployment is not needed. We have been using it for tests  ethers-deploy library and this library should also be used for actual deployment, that is what it is made for, there is no point in having extra scripts/deployer  script and running it. Please advise If I am missing something here and why it was used.

**Comment by n00b21337** [comment]
This is done and deployed.
