### ISSUE TITLE
Allow setting the gas fee for transactions

### ISSUE THREAD

**Issue by mrekucci** [ethersphere/storage-incentives#88]
Add command line parameters to set `maxPriorityFeePerGas`, `maxFeePerGas`, and `gasLimit` for transactions.

```JS
const tx = {
    // ...
    maxPriorityFeePerGas: BigInt(feeData['maxPriorityFeePerGas']), // Recommended maxPriorityFeePerGas.
    maxFeePerGas: feeData['maxFeePerGas'], // Recommended maxFeePerGas.
    gasLimit: '21000', // Basic transaction costs exactly 21000.
    // ...
  };
```

**Comment by significance** [comment]
@n00b21337 is this superseded by new deployment methodology?

**Comment by n00b21337** [comment]
I could add this as commented out block if needed to have it by hand  but shouldn't be needed. This is useful when you have congested chain like ethereum and you dont want to get auto gas set but you want to get it higher then most. Again as gnosis chain is low on gas and traffic, this will be mostly obsolete.

**Comment by n00b21337** [comment]
This is obsolete with current framework
