### ISSUE TITLE
Cancel Pending Transaction

### ISSUE THREAD

**Issue by mrekucci** [ethersphere/storage-incentives#89]
Enhance the smart-contracts deployment scripts with the ability to cancel an ongoing transaction.
Allow setting the `timeout` and `txHash` for the ongoing transaction as command line parameters.

**Comment by significance** [comment]
@n00b21337 close in favour of new deployment methodology?

**Comment by n00b21337** [comment]
With implementing fully https://github.com/wighawag/hardhat-deploy
this is covered as this library offers to do that or speed up trx
